### ISSUE TITLE
chalk tried to access #ansi-styles, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by dobesv** [bmish/check-dependency-version-consistency#538]
After updating to the latest version, the tool cannot be run in a yarn PnP environment because of this error:

```
$ yarn check-dependency-version-consistency --ignore-dep immutable .
/home/ubuntu/app2/.pnp.cjs:60925
  return Object.defineProperties(new Error(message), {
                                 ^

Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.1 (via /home/ubuntu/app2/.yarn/cache/chalk-npm-5.0.1-6afcb94227-7b45300372.zip/node_modules/chalk/source/index.js)

    at makeError (/home/ubuntu/app2/.pnp.cjs:60925:34)
    at resolveToUnqualified (/home/ubuntu/app2/.pnp.cjs:61844:21)
    at Object.resolveToUnqualified (/home/ubuntu/app2/.pnp.cjs:61988:26)
    at resolve$1 (file:///home/ubuntu/app2/.pnp.loader.mjs:224:31)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I haven't seen this `#ansi-styles` import style before.  I do see a package called `ansi-styles` in NPM, though.  Any idea?

**Comment by dobesv** [comment]
Maybe if you depend on chalk < 5 we avoid the issues caused by their insistence on using ESM only?

**Comment by dobesv** [comment]
I guess this might be more of a problem with chalk than with this package, though.  Hm.

**Comment by bmish** [comment]
I think this is an external problem, try the workaround here:

https://github.com/chalk/chalk/issues/531#issuecomment-1146705502

**Comment by dobesv** [comment]
Thanks
